name: QEMU Build
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: mkdir -p output
      - name: Build Builder
        uses: docker/build-push-action@v3
        with:
          context: test/qemu-builder/
          file: test/qemu-builder/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha
          outputs: type=local,dest=output
          tags: local/builder:latest
      - name: Build
        run: |
          mkdir -p output
          docker buildx run --rm -v $PWD/output:/work/output local/builder:latest /bin/sh -c 'dpkg-buildpackage -d -uc -us && cd /work && cp -rf qemu-*.*deb qemu_8.0.4+dfsg-1ubuntu5.dsc qemu_8.0.4+dfsg-1ubuntu5_amd64.buildinfo qemu_8.0.4+dfsg-1ubuntu5_amd64.changes /work/output'
      - uses: actions/upload-artifact@v3
        with:
          path: |
            output/*

