name: Test

on:
  pull_request: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tar git make gcc qemu-system-x86
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Base Tools
        run: make -C edk2/BaseTools
