name: Test

on:
  pull_request: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tar git make gcc nasm mtools qemu-system-x86
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Base Tools
        run: |
          git submodule update --init
          (cd edk2 && git submodule update --init -- BaseTools/Source/C/BrotliCompress/brotli/ MdePkg/Library/MipiSysTLib/mipisyst/)
          make -C edk2/BaseTools

      - name: Test in qemu
        run: |
          ./scripts/run-5s.sh
          touch .tmp/report.md
          echo "<details>" >> .tmp/report.md
          echo "<summary>debug.log</summary>" >> .tmp/report.md
          echo "```" >> .tmp/report.md
          cat .tmp/debug.log >> .tmp/report.md
          echo "```" >> .tmp/report.md
          echo "</details>" >> .tmp/report.md

          echo >> .tmp/report.md

          echo "<details>" >> .tmp/report.md
          echo "<summary>serial.log</summary>" >> .tmp/report.md
          echo "```" >> .tmp/report.md
          cat .tmp/serial.log >> .tmp/report.md
          echo "```" >> .tmp/report.md
          echo "</details>" >> .tmp/report.md

          echo >> .tmp/report.md

          echo "<details>" >> .tmp/report.md
          echo "<summary>kern.log</summary>" >> .tmp/report.md
          echo "```" >> .tmp/report.md
          cat .tmp/kern.log >> .tmp/report.md
          echo "```" >> .tmp/report.md
          echo "</details>" >> .tmp/report.md


      - name: Create Comment
        id: comment
        if: ${{ github.event.issue.pull_request }}
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: "${{ inputs.issue-number }}"
          body-path: ".tmp/report.md"

